---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
  become: true
  tasks:
    - name: List existing UFW rules
      ansible.builtin.command: ufw status numbered
      register: ufw_status
      changed_when: false

    - name: Retrieve ufw state and set expected state
      ansible.builtin.set_fact:
        ufw_rules: "{{ ufw_status.stdout | community.general.jc('ufw') }}"
        ufw_rules_expected:  [
            {
                "action": "ALLOW",
                "action_direction": "OUT",
                "comment": null,
                "from_interface": "any",
                "from_ip": "0.0.0.0",
                "from_ip_prefix": 0,
                "from_service": "(out)",
                "from_transport": null,
                "index": 1,
                "network_protocol": "ipv4",
                "to_interface": "any",
                "to_ip": "172.16.0.0",
                "to_ip_prefix": 12,
                "to_ports": [
                    2020
                ],
                "to_service": null,
                "to_transport": "any"
            },
            {
                "action": "ALLOW",
                "action_direction": "OUT",
                "comment": null,
                "from_interface": "any",
                "from_ip": "0.0.0.0",
                "from_ip_prefix": 0,
                "from_service": "(out)",
                "from_transport": null,
                "index": 2,
                "network_protocol": "ipv4",
                "to_interface": "any",
                "to_ip": "8.5.5.6",
                "to_ip_prefix": 32,
                "to_ports": [
                    2020
                ],
                "to_service": null,
                "to_transport": "any"
            }
        ]

    - name: Display ufw state
      ansible.builtin.debug:
        msg: "{{ ufw_rules.rules }}"

    - name: Ensure no difference in expected and current state
      ansible.builtin.assert:
        that: "(ufw_rules.rules | difference(ufw_rules_expected)) == []"
        msg: "Failed difference: {{ (ufw_rules.rules | difference(ufw_rules_expected)) }}"
